config/routes.rb
Rails.application.routes.draw do
    root to: 'static_pages#home'
    get 'admin/login', to: 'admin/sessions#new'
    post 'admin/login', to: 'admin/sessions#create'
    delete 'admin/logout', to: 'admin/sessions#destroy'
    get 'tie', to: 'static_pages#tie'
    get 'menu', to: 'static_pages#menu'
    get 'yoyaku', to: 'static_pages#yoyaku'
    
    get 'contact', to: 'static_pages#contact'
  
    resources :messages, only: [:index, :show]
    
  
    namespace :admin do
      resources :messages
    end
    
end    
     
    

app/models/message.rb
class Message < ActiveRecord::Base
  # タイトルは必須入力
  validates :title ,  presence: true
  # 内容は必須入力
  validates :body ,  presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
  
  before_action :logged_in_user
  
  
  def index
    # Messageを全て取得する。
  
    
    @messages = Message.all.order(created_at: :desc).page(params[:page]).per(10) # この行を追加
  end
  
  def new
    @message = Message.new
  end  

  def create
    @message = Message.new(message_params)
    
    if @message.save
    
    
    redirect_to admin_messages_path , notice: 'メッセージを保存しました'
    
    else
      #  保存に失敗した場合は編集画面へ戻す
      render  'new'
    end
  end
  
  def edit
      @message = Message.find(params[:id])
  end
          # メッセージの編集
  def update
      @message = Message.find(params[:id])
      if @message.update(message_params)
      #  保存に成功した場合はトップページへリダイレクト 
      redirect_to admin_messages_path , notice: 'メッツセージを編集しました。'
    else
      #  保存に失敗した場合は編集画面へ戻す
      render  'edit'
    end
  end
  
  
  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to admin_messages_path , notice: 'メッセージを削除しました'
  end  
  
  private
  
  def message_params
    params.require(:message).permit(:title, :body)
  end
end


    

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  def new
    @admin = User.new
  end
  
   def create
    @user = User.find_by(email: params[:user][:email].downcase, admin: true)
       # binding.pry
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to admin_messages_url
    else
      flash[:danger] = 'invalid email/password combination'
      @admin = User.new 
      
      
      
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include ApplicationHelper
  
  
  protect_from_forgery with: :exception
  
    private
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to admin_login_url
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def index
    # Messageを全て取得する。
    
    @messages = Message.all.order(created_at: :desc).page(params[:page]).per(10) # この行を追加
  end
  
  def show
     @message = Message.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  
  
  def home
    
    
   @messages = Message.all.order(created_at: :desc).page(params[:page]).per(5) # この行を追加    
    
    
    
  end
  
  def tie
  end
  
  def menu
  end
  

  def contact
  end    
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    
    
    def current_user
    p session[:user_id]
    p "msg"
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end 
    
    
end

app/views/admin/messages/_form.html.erb
<%= link_to "メッセージ一覧ページ" , admin_messages_path %>
<%= form_for([:admin, @message], html: {class: "form-horizontal"}) do |f| %>

<% if @message.errors.present? %>
    <div class="alert alert-danger">
        <%= alert %>
        <ul>
            <% @message.errors.full_messages.each do |full_message| %>
              <li>
                <%= full_message %>
              </li>
            <% end %> 
        </ul>
    </div>
<% end %>

<div class="form-group">
        <label for="message_title" class="control-label col-md-2">タイトル:</label>
        <div class="col-md-10">
            <%= f.text_field :title, class: "form-control" %>
        </div>
</div>

<div class="form-group">
        <label for="message_body" class="control-label col-md-2">内容:</label>
        <div class="col-md-10">
            <%= f.text_area :body,rows: 5, class: "form-control" %>
        </div>
</div>

<%#= link_to "edit admin", edit_admin_message_path(@message) %>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        
    
    <%= f.submit class: "btn btn-sm btn-primary" %>  
    </div>   
</div>
  
<% end %>  

app/views/admin/messages/edit.html.erb
<h1>メッセージの編集</h1>


<%= render 'form' %>

app/views/admin/messages/index.html.erb
<h1>管理ページ</h1>
<div class="panel panel-default">
    
   <div class="panel-heading">
      メッセージ一覧
      <%= link_to "新規作成" , new_admin_message_path , class: "pull-right" %>
   </div>
   
   <div class="panel-body">
      <% @messages.each do |message| %>
        <%= link_to message.title, message_path(message) %>
        
        (<%= link_to "edit" , edit_admin_message_path(message) %>
          <%= link_to "destory" , admin_message_path(message) , method: :delete, data: { confirm: '削除してもよろしいですか？'}%>
         )
        <br>
        
        
        
      <% end %>
      
      
   </div>
   <%= paginate @messages %>
</div>

app/views/admin/messages/new.html.erb
<h1>メッセージの新規作成</h1>

<%= render 'form' %>

app/views/admins/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@admin) do |f| %>

     
      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
       <%= link_to "ぞうのみみ", root_path, id: "logo", class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "タイ古式", tie_path %></li>
        <li><%= link_to "メニュー＆料金", menu_path %></li>
        <li><%= link_to "ブログ", "http://ameblo.jp/zounomimi1121/" ,target: "_blank" %></li>
        <li><%= link_to "お問合せ＆アクセス", contact_path %></li>
        <li><%= link_to "予約メニュー", yoyaku_path %></li>
        <li><%= link_to "お知らせ一覧", messages_path %></li>
        
        <% if logged_in? %>
          
          <li><%= link_to "管理ページ", admin_messages_path %></li>
        
          <li><%= link_to "Log out", admin_logout_path, method: "delete" %></li>
        
        
        <% end %>
        
        
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<h3> 本場タイで学んできました<br>タイ古式リラクゼーション</h3>
<h2> タイ政府公認終了証書取得</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ぞうのみみ</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<h1>お知らせ一覧</h1>

<% @messages.each do |message| %>

<%= link_to message.title, message_path(message) %>
  
  <br>
<% end %>
<%= paginate @messages %>

app/views/messages/show.html.erb
<h1>お知らせ詳細</h1>

<span class="label label-info"><%= @message.title %></span>

<%= simple_format @message.body %>


  

app/views/static_pages/contact.html.erb
<div class="page-header">
  <h1 class="toiawase">お問い合わせ・アクセス</h1>
    <div class="table-responsive">
      <table class="table table-striped table-bordered">
          <div class="row">
            
          </div>
          <tr>
            <td class="col-md-4"> 社　名</td>
            <td class="col-md-8"> ぞうのみみ</td>
          </tr>
          <tr>
            <td>代 表</td>
            <td>まぁ坊</td>
          </tr>
          <tr>
            <td>店舗名</td>
            <td>ゾウノミミ</td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td>〒761-　　　</td>
          </tr>
          <tr>
            <td>住所</td>
            <td>香川県高松市</td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td>080-3923-1803</td>
          </tr>
          <tr>
            <td>zouno_mimi_1121@yahoo.co.jp</td>
            <td>03-0000-0002</td>
          </tr>
          <tr>
            <td>営業時間</td>
            <td>11時～20時（最終受付19時）</td>
          </tr>
          <tr>
            <td>定休日</td>
            <td>水曜日・祝日</td>
          </tr>
          <tr>
            <td>アクセス方法</td>
            <td>詳しい場所は、ご予約の際お問い合わせ下さい。</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
 
 <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d1872.6293286896082!2d139.70500058762033!3d35.660790077392356!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sja!2sjp!4v1479975432111" width="100%" height="600" frameborder="0" style="border:0" allowfullscreen></iframe>

app/views/static_pages/home.html.erb
<div id="mainview" ><%= image_tag("mainview.jpg") %></div>  



<div class="panel panel-default">
    
   <div class="panel-heading">
      お知らせ一覧
   
   </div>
   
   <div class="panel-body">
      <% @messages.each do |message| %>
        <%= link_to message.title, message_path(message) %>
        <br>
   <% end %>
   <div class="text-center">
      <%=link_to '続きを見る',messages_path %>
   </div>      
   </div>

</div>

app/views/static_pages/menu.html.erb
<header>
    <div id="logo">
        
        <h1>メニュー&料金</h1>
    </div>
</header>
<div class="container">
    <div id="logo">
        <%= image_tag 'menu01.jpg' %>
    </div>    
    <section>
        <h1>　メニュー＆料金？</h1>
        <p>６０分　４５００円</p>
        <p>９０分　６５００円</p>
　　　　　　　　<p>１２０分８５００円</p>
　　　　　　　　<p></p>
        <p>※　ゆったりとした施術でリフレッシュしていただくために、９０分をお勧めいたします。</p>
        <p>施術中、リラックスしていただくため</p>
        <p>音楽をかけていますが</p>
        <p>当店では、お客様自身でリラックス出来る音楽を</p>
        <p>お持ちいただければ、再生出来るようにしております。</p>
        <p>レコード・ＣＤ・音楽プレーヤーなどに対応してますので</p>
        <p>ご自身でリラックス出来る音楽をお持ちください。</p> 
    <div id="logo">
        <%= image_tag 'menu02.jpg' %>
    </div>        
        
        
        <h1>施術の流れ</h1> 
        <p>メールまたはお電話にてご予約</p> 
        <p>↓</p> 
        <p>当店より折り返しのメールありましたら、ご予約完了になります。</p> 
        <p>↓</p> 
        <p>ご来店</p>  
        <p>↓</p> 
        <p>問診</p>  
        <p>まずお茶を飲んでいただきなからお客様のお体の事など、いろいろお教え下さい。</p> 
        <p>↓</p> 
        <p>問診が終わりましたら、お着替えをしていただきます。</p>  
        <p></p>
    <div id="logo">
        <%= image_tag 'menu03.jpg' %>
    </div> 
        <p>次は、足湯です。</p> 
        <p>いろいろな香りを用意させていただいておりますので</p> 
        <p>お好みの香りで足湯を楽しんでいただけます。</p>
        <p>↓</p>
        <p>足湯が終わりましたら、広めのマットでゆったりと横になっていただき施術開始です。</p> 
        <p>↓</p>
        <p>施術が終わるとお茶の時間です。</p> 
        <p>何種類かのお飲み物の中からお選び下さい。お菓子や果物もご一緒にいかがですか？</p>
        <p>※足湯や、お茶の時間は、サービスです。 コースのお時間には含まれません。</p> 
        <p>コースのお時間＋１時間ほどお考え下さい。</p> 
        <p></p>
        <p>お急ぎの方は、初めにお伝えいただけますと、助かります。<p>
    </section>
</div>

app/views/static_pages/tie.html.erb
<header>
    <div id="logo">
        
        <h1>タイ古式とは</h1>
    </div>
</header>
<div class="container">
    
    <section>
        <h1>　タイ古式とは？</h1>
        <p>体に「セン」というエナジーラインがあり疲れなどでこのエナジーラインが</p>
        <p>乱れ体や、気持ちに不調が出てしまうのを「タイ古式リラクゼーション」を用いて</p>
　　　　　　　　<p>「セン」の流れをスムーズに良い方向に持っていこうというものです。</p>
        <p>いたいイメージのある「タイ古式」ですがお客様のお身体の硬さに</p>
        <p>合わせて手技を調整いたします。</p> 
    <div id="logo">
        <%= image_tag 'top.jpg' %>
    </div>     
        <p></p> 
        <h1>タイ古式リラクゼーションってどんなの？</h1>
        <p>タイ古式リラクゼーションは凝りをほぐすだけでなく</p>
        <p>全身の血行をあげ、体の細胞のすみずみまで酸素や栄養を運び</p>
　　　　　　　　<p>本来の体調を取り戻すことで</p>
        <p>本来持っている治癒力を回復、高めて、精神と肉体の健康を取り戻していきます。</p>
        <p>部分的な施術というよりは</p> 
        <p>ゆっくりと時間をかけて全身を施術していきます。</p>
        <p>タイ古式リラクゼーションテクニックもさまざまで</p> 
        <p>指圧のような母指や手のひらを使った圧迫以外に</p> 
        <p>肘や足、ひざを使ったテクニックや、血止めのテクニック、ストレッチテクニックも</p> 
        <p>タイ古式リラクゼーションの特徴です。</p> 
           
        <h1>他のマッサージとの違いは？</h1> 
    <div id="logo">
        <%= image_tag 'tiekosiki01.jpg' %>
    </div>     

        <p>本来2時間かけて全身の施術を行います。</p> 
        <p>まず、スタートは足から。</p> 
        <p>脚部分の施術だけでも40分から1時間以上かけます。</p> 
    <div id="logo">
        <%= image_tag 'tiekosiki02.jpg' %>
    </div>     
        
        <p>次は、腕、腹部、腰、背中、肩、首、顔や頭など施術をおこなって行きます。</p>
     <div id="logo">
        <%= image_tag 'tiekosiki03.jpg' %>
    </div>    
        <p>途中や最後に、ストレッチをおこないます。</p>
        *お客様とお話しして、施術時間や重点的に施術する部分は調整します。</p>
    </section>

</div>

app/views/static_pages/yoyaku.erb
<a href="https://coubic.com/zounomimiyoyaku/services" target="_blank">
    <img src="https://d3d490cizl1cnr.cloudfront.net/buttons/reservation_button_01.png" alt="クービック予約システムから予約する" width="128" height="32"></a>
    <h3>予約はこのボタンでお願いします。</h3>